# 镜像同步服务配置文件示例
# 复制此文件为 config.yaml 并根据需要修改配置

# GitHub 配置
github:
  token: ""                    # GitHub Token，也可通过环境变量 GITHUB_TOKEN 设置
  user: ""                     # GitHub 用户名，也可通过环境变量 GITHUB_USER 设置
  repo: ""                     # GitHub 仓库名，也可通过环境变量 GITHUB_REPO 设置
  run_id: ""                   # GitHub Actions Run ID，也可通过环境变量 GITHUB_RUN_ID 设置

# Docker 配置
docker:
  registry: ""                 # Docker 注册表地址，也可通过环境变量 DOCKER_REGISTRY 设置
  namespace: ""                # Docker 命名空间，也可通过环境变量 DOCKER_NAMESPACE 设置
  username: ""                 # Docker 用户名，也可通过环境变量 DOCKER_USER 设置
  password: ""                 # Docker 密码，也可通过环境变量 DOCKER_PASSWORD 设置
  platforms: "linux/amd64,linux/arm64"  # 支持的平台架构

# 华为云 SWR 配置
huawei_swr:
  access_key: ""               # 华为云 Access Key，也可通过环境变量 AK 设置
  secret_key: ""               # 华为云 Secret Key，也可通过环境变量 SK 设置
  region: "cn-southwest-2"     # 华为云区域，也可通过环境变量 HUAWEI_REGION 设置

# 镜像转换规则
rules:
  "^gcr.io": ""
  "^k8s.gcr.io": "google-containers"
  "^registry.k8s.io": "google-containers"
  "^quay.io": "quay"
  "^ghcr.io": "ghcr"
  "^docker.io": "docker"

# 应用程序配置
app:
  log_level: "info"            # 日志级别: debug, info, warn, error
  debug: false                 # 是否启用调试模式
