# 镜像同步服务配置文件示例
# 复制此文件为 config.yaml 并根据需要修改配置

# GitHub 配置
github:
  token: "" # GitHub Token，也可通过环境变量 GITHUB_TOKEN 设置
  user: "" # GitHub 用户名，也可通过环境变量 GITHUB_USER 设置
  repo: "" # GitHub 仓库名，也可通过环境变量 GITHUB_REPO 设置
  run_id: "" # GitHub Actions Run ID，也可通过环境变量 GITHUB_RUN_ID 设置

# 平台架构配置
platforms: "linux/amd64,linux/arm64" # 支持的平台架构，也可通过环境变量 PLATFORMS 设置

# 统一仓库配置（所有仓库都使用通用处理器）
# 系统自动检测目标仓库类型并应用相应的特殊处理逻辑
registries:
  # 华为云 SWR 配置（可选，用于自动设置镜像公开权限）
  # 如果配置了，系统会在推送到华为云SWR后自动设置镜像为公开访问
  huawei_swr:
    access_key: "" # 华为云 Access Key，也可通过环境变量 HUAWEI_SWR_ACCESS_KEY 设置
    secret_key: "" # 华为云 Secret Key，也可通过环境变量 HUAWEI_SWR_SECRET_KEY 设置
    region: "cn-southwest-2" # 华为云区域，也可通过环境变量 HUAWEI_SWR_REGION 设置
  # 通用仓库配置（适用于所有仓库：Docker Hub、华为云SWR、私有仓库等）
  # 所有仓库都使用统一的通用处理器，华为云会自动应用特殊处理
  # generic:
  #   registry: ""             # 仓库地址，如 docker.io，也可通过环境变量 GENERIC_REGISTRY 设置
  #   namespace: ""            # 命名空间，也可通过环境变量 GENERIC_NAMESPACE 设置
  #   username: ""             # 用户名，也可通过环境变量 GENERIC_USERNAME 设置
  #   password: ""             # 密码或访问令牌，也可通过环境变量 GENERIC_PASSWORD 设置

  # 使用示例：
  # 1. Docker Hub：
  #    registry: "docker.io"
  #    username: "your_docker_username"
  #    password: "your_docker_password_or_token"
  #
  # 2. 私有仓库：
  #    registry: "your-private-registry.com"
  #    username: "your_username"
  #    password: "your_password"

  # 镜像转换规则
rules:
  "^gcr.io": ""
  "^k8s.gcr.io": "google-containers"
  "^registry.k8s.io": "google-containers"
  "^quay.io": "quay"
  "^ghcr.io": "ghcr"
  "^docker.io": "docker"

# 应用程序配置
app:
  log_level: "info" # 日志级别: debug, info, warn, error
  debug: false # 是否启用调试模式

# 架构说明：
# - 所有仓库都使用统一的通用处理器
# - 推送完成后会自动执行适用的后处理操作
# - 华为云SWR会自动应用后处理（设置镜像公开权限）
# - 华为云配置是可选的，如果未配置，镜像将保持默认状态
# - 通用配置支持匿名访问公共仓库
# - 后处理机制支持扩展其他云服务商的特殊处理
