name: sync_image

on:
  issues:
    types: [opened, edited]
  label:
    types: [created]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  sync:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'porter')

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 QEMU 环境
        uses: docker/setup-qemu-action@v3

      - name: 拉取同步镜像
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "使用镜像: $IMAGE"
          docker pull $IMAGE

      - name: 运行镜像同步
        env:
          HUAWEI_SWR_ACCESS_KEY: ${{ secrets.HUAWEI_SWR_ACCESS_KEY }}
          HUAWEI_SWR_SECRET_KEY: ${{ secrets.HUAWEI_SWR_SECRET_KEY }}
          HUAWEI_SWR_REGION: ${{ secrets.HUAWEI_SWR_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GENERIC_REGISTRY: ${{ secrets.GENERIC_REGISTRY }}
          GENERIC_NAMESPACE: ${{ secrets.GENERIC_NAMESPACE }}
          GENERIC_USERNAME: ${{ secrets.GENERIC_USERNAME }}
          GENERIC_PASSWORD: ${{ secrets.GENERIC_PASSWORD }}
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

          echo "使用镜像: $IMAGE"
          echo "配置信息:"
          echo "  GitHub User: ${GITHUB_USER}"
          echo "  GitHub Repo: ${GITHUB_REPO}"
          echo "  GitHub Run ID: ${GITHUB_RUN_ID}"
          echo "  Generic Registry: ${GENERIC_REGISTRY}"
          echo "  Generic Namespace: ${GENERIC_NAMESPACE}"

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --privileged \
            -e HUAWEI_SWR_ACCESS_KEY="${HUAWEI_SWR_ACCESS_KEY}" \
            -e HUAWEI_SWR_SECRET_KEY="${HUAWEI_SWR_SECRET_KEY}" \
            -e HUAWEI_SWR_REGION="${HUAWEI_SWR_REGION}" \
            -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
            -e GITHUB_USER="${GITHUB_USER}" \
            -e GITHUB_REPO="${GITHUB_REPO}" \
            -e GITHUB_RUN_ID="${GITHUB_RUN_ID}" \
            -e GENERIC_REGISTRY="${GENERIC_REGISTRY}" \
            -e GENERIC_NAMESPACE="${GENERIC_NAMESPACE}" \
            -e GENERIC_USERNAME="${GENERIC_USERNAME}" \
            -e GENERIC_PASSWORD="${GENERIC_PASSWORD}" \
            -e DOCKER_BUILDKIT=1 \
            -e DOCKER_CLI_EXPERIMENTAL=enabled \
            $IMAGE \
            --config=/app/configs/rules.yaml

  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: check issues
        id: check_issues
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const openIssues = await github.issues.listForRepo({
                  owner: '${{ github.repository_owner }}',
                  repo: '${{ github.event.repository.name }}',
                  state: 'open',
                  per_page: 100,
                  sort: "created",
                  direction: "desc",
            })
            
            if (!Array.isArray(openIssues["data"]) || !openIssues["data"].length) {
              core.setOutput('SUCCESS', true)
              return
            }
            let validLabels=false
            for(let issues of openIssues['data']){
                for(let labels of issues["labels"]){
                  if(labels["name"]=="porter" || labels["name"]=="question"){
                    validLabels=true
                  }
                }
                if(validLabels){
                  continue
                }
                await  github.issues.createComment({
                  owner: '${{ github.repository_owner }}',
                  repo: '${{ github.event.repository.name }}',
                  issue_number: issues["number"],
                  body: "@"+issues["user"]["login"]+" 不是说了嘛，通过模板创建 issues，请通过[此模板](https://github.com/tw-ops/sync_image/issues/new?assignees=&labels=porter&template=porter.md&title=%5BPORTER%5D)重新创建，此 issues 将自动关闭"
                });
                await github.issues.addLabels({
                  owner: '${{ github.repository_owner }}',
                  repo: '${{ github.event.repository.name }}',
                  issue_number: issues["number"],
                  labels: ["rude"]
                });
              await github.issues.update({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.event.repository.name }}',
                issue_number: issues["number"],
                state: 'closed'
                })
            }
